---
name: Java CI

on: [push, pull_request]

jobs:
  analyzerJob:
    runs-on: ubuntu-latest
    name: A job to say thank you
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Analyzer
        id: hello
        uses: Remoliveira/id-analyzer-action4@v3
